M48
; DRILL file {KiCad 7.0.5-4d25ed1034~172~ubuntu22.04.1} date Rab 05 Jul 2023 09:03:01 
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-05T09:03:01+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-4d25ed1034~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X86.66Y-55.782
X90.66Y-55.782
T2
X80.93Y-96.09
T3
X99.91Y-55.4
T0
M30
